version: '3.4'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: Heslo1234.
      POSTGRES_USER: Admin
      POSTGRES_DB: StihamToDb
    ports:
      - '5455:5432'
    volumes: 
      - data:/var/lib/postgresql/data

volumes:
  data:
